<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.361">
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MaxMind.GeoIP2" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="GeoLite2-Country.mmdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
